namespace AircraftMaintenanceOperations.Application.Features.MaintenanceRequests.Commands.ArchiveMaintenanceRequest;

public record ArchiveMaintenanceCommand(Guid MaintenanceRequestId) : ICommand<ArchiveMaintenanceResult>;
public record ArchiveMaintenanceResult(bool IsArchived);
