<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Aircraft\Mappings\" />
    <Folder Include="Features\Inventory\" />
    <Folder Include="Features\Authentication\" />
    <Folder Include="Features\WorkOrders\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.18" />
    <PackageReference Include="Microsoft.VisualStudio.Language.Intellisense" Version="17.14.249" />
    <PackageReference Include="System.ObjectModel" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AircraftMaintenanceOperations.Domain\AircraftMaintenanceOperations.Domain.csproj" />
  </ItemGroup>

</Project>
